server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ams-auth
              uri: http://localhost:8081 
              predicates:
                - Path=/api/auth/**
              
            - id: ams-data
              uri: http://localhost:8083 
              predicates:
                - Path=/api/data/**

